"""empty message

Revision ID: 3b45dc6843ec
Revises: 
Create Date: 2025-07-19 17:30:31.635942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b45dc6843ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=200), nullable=True))
        batch_op.alter_column('score',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('transcription',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('analysis',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('analysis',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('transcription',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('pdf_path')

    # ### end Alembic commands ###
