"""Add hired to Report

Revision ID: d44dd2ff9309
Revises: 3b45dc6843ec
Create Date: 2025-07-19 17:52:41.425099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44dd2ff9309'
down_revision = '3b45dc6843ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hired', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('hired')

    # ### end Alembic commands ###
